# Generated by Django 2.2 on 2021-08-03 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='retailer',
            name='city',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='retailer',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='specialty',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='type',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to='main.User'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
