# Generated by Django 2.2 on 2021-08-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='following',
        ),
        migrations.AddField(
            model_name='follower',
            name='first_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='last_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
